/// Flutter icons MyFlutterApp
/// Copyright (C) 2025 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  BankIcons
///      fonts:
///       - asset: fonts/BankIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class BankIcons {
  BankIcons._();

  static const _kFontFam = 'BankIcons';
  static const String? _kFontPkg = null;

  static const IconData au = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData anz = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData yes_bank = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData union = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData idfc = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData anz_1 = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData airtel_payments = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sbi = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pnb = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData paytm = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData kotak = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData induslnd = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData idbi = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icici = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hsbc = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hdfc = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData deutsche_bank = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData citi_bank = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData boi = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bob = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData axis_bank = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
